language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install: pip install -r requirements.txt
script:
  - py.test --doctest-modules -v surt/
  - pylint --disable=all --enable=W0312 --reports=n surt/
